# Setup
title:               Michael B. Cerny
tagline:             'Harvard University'
description:         'Michael B. Cerny&#39s website.'
url:                 https://michaelbcerny.net
baseurl:             ''
paginate:            5
paginate_path: "/page:num/"
permalink:           pretty
future: true

# About/contact
author:
  name:              Michael B. Cerny
  url:               michaelbcerny.github.io
  email:             michael_cerny@g.harvard.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
